# Generated by Django 3.2.1 on 2023-01-24 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(max_length=50)),
                ('departamento_municipio', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.CASCADE, to='GlobalApi.departamentos')),
            ],
        ),
        migrations.CreateModel(
            name='PuestoVotacion',
            fields=[
                ('id_puesto_votacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_puesto_votacion', models.CharField(max_length=50)),
                ('direccion_puesto_votacion', models.CharField(max_length=100)),
                ('municipio_puesto_votacion', models.ForeignKey(db_column='id_municipio', on_delete=django.db.models.deletion.CASCADE, to='GlobalApi.municipios')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('doc', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Numero de documento')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de usuario')),
                ('user_type', models.CharField(max_length=1, verbose_name='Tipo usuario')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo electronico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Votantes',
            fields=[
                ('id_votante', models.AutoField(primary_key=True, serialize=False)),
                ('doc_votante', models.CharField(max_length=50)),
                ('nombres_votante', models.CharField(max_length=50)),
                ('apellidos_votante', models.CharField(max_length=100)),
                ('direccion_votante', models.EmailField(max_length=254)),
                ('ciudad_votante', models.CharField(max_length=50)),
                ('puesto_votacion', models.ForeignKey(db_column='id_puesto_votacion', on_delete=django.db.models.deletion.CASCADE, to='GlobalApi.puestovotacion')),
            ],
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('id_lider', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_lider', models.CharField(max_length=50)),
                ('apellidos_lider', models.CharField(max_length=100)),
                ('direccion_lider', models.EmailField(max_length=254)),
                ('ciudad_lider', models.CharField(max_length=50)),
                ('foto_lider', models.ImageField(blank=True, null=True, upload_to='lideres')),
                ('email_lider', models.EmailField(max_length=254)),
                ('doc_lider', models.ForeignKey(db_column='doc', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('name_admin', models.CharField(max_length=50)),
                ('last_name_admin', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('doc_admin', models.ForeignKey(db_column='doc', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
