# Generated by Django 3.2.1 on 2023-01-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GlobalApi', '0002_user_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='foto_usuario',
        ),
    ]
