# Generated by Django 3.2.1 on 2023-01-25 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GlobalApi', '0006_lider_cantidad_votantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votantes',
            name='ciudad_votante',
        ),
        migrations.AddField(
            model_name='municipios',
            name='cantidad_votantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='puestovotacion',
            name='cantidad_votantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='votantes',
            name='municipio_votante',
            field=models.ForeignKey(db_column='id_municipio', default=1, on_delete=django.db.models.deletion.CASCADE, to='GlobalApi.municipios'),
            preserve_default=False,
        ),
    ]
