# Generated by Django 3.2.1 on 2023-01-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlobalApi', '0007_auto_20230125_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='lider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
