# Generated by Django 3.2.1 on 2023-01-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlobalApi', '0008_lider_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lider',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
