# Generated by Django 3.2.1 on 2023-01-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlobalApi', '0013_alter_lider_doc_lider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='id_departamento',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lider',
            name='id_lider',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='id_municipio',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='puestovotacion',
            name='id_puesto_votacion',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='votantes',
            name='id_votante',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
