# Generated by Django 3.2.1 on 2023-01-26 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GlobalApi', '0014_auto_20230126_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lider',
            name='doc_lider',
            field=models.ForeignKey(db_column='doc', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
